// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;

namespace Xenko.Rendering
{
    public static partial class FoveaEffectKeys
    {
        public static readonly ValueParameterKey<Vector2> OneOverTexSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<bool> UseSharpening = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<float> Sharpening = ParameterKeys.NewValue<float>(-0.175f);
    }
}
