// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class HandEffectKeys
    {
        public static readonly ValueParameterKey<Matrix> MatrixTransform = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> View = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> Joints = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<float> Opacity = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Vector3> SpecularLightDirection = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,1.0f,0.0f));
        public static readonly ValueParameterKey<Color3> SpecularLightColor = ParameterKeys.NewValue<Color3>(new Color3(0.01f,0.0075f,0.006f));
        public static readonly ValueParameterKey<Color3> AmbientLightColor = ParameterKeys.NewValue<Color3>(new Color3(0.001f,0.001f,0.001f));
        public static readonly ValueParameterKey<Color3> GlowColor = ParameterKeys.NewValue<Color3>(new Color3(0.0f,0.0f,0.0f));
    }
}
