// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class LightSpriteEffectKeys
    {
        public static readonly ValueParameterKey<Matrix> View = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> WorldView = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector3> LightDirectionWS = ParameterKeys.NewValue<Vector3>(new Vector3(0,-1,0));
        public static readonly ValueParameterKey<Color3> LightColor = ParameterKeys.NewValue<Color3>(new Color3(1,1,1));
        public static readonly ValueParameterKey<Color4> Color = ParameterKeys.NewValue<Color4>(new Color4(1,1,1,1));
        public static readonly ValueParameterKey<Color3> AmbientColor = ParameterKeys.NewValue<Color3>(new Color3(0,0,0));
        public static readonly ValueParameterKey<float> SpecularPower = ParameterKeys.NewValue<float>(20);
    }
}
